<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_SecondBin</name>
   <tag></tag>
   <elementGuidId>6509a7c2-2627-40d6-9185-e3671ce72539</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;site_ec041b07-3a2f-41f5-9fac-fe437e626c50&quot;)/div[@class=&quot;opi-panel&quot;]/div[@class=&quot;panel-content&quot;]/div[@class=&quot;site-header flex-row xs-flex-column-start-start&quot;]/site-viz[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;site-display-mount&quot;]/div[@class=&quot;site-viz mt-2&quot;]/div[@class=&quot;horizontal-scroll-container&quot;]/svg[@class=&quot;site-viz-svg&quot;]/g[1]/g[2]/g[@class=&quot;cursor-pointer&quot;]/text[1][count(. | //text[@dx = '27.5' and @dy = '58' and @text-anchor = 'middle' and @font-family = 'Verdana' and @font-size = '12' and @fill = '#F45337' and (text() = 'SecondBin' or . = 'SecondBin')]) = count(//text[@dx = '27.5' and @dy = '58' and @text-anchor = 'middle' and @font-family = 'Verdana' and @font-size = '12' and @fill = '#F45337' and (text() = 'SecondBin' or . = 'SecondBin')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dx</name>
      <type>Main</type>
      <value>27.5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>58</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-anchor</name>
      <type>Main</type>
      <value>middle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-family</name>
      <type>Main</type>
      <value>Verdana</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>12</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#F45337</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SecondBin</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site_ec041b07-3a2f-41f5-9fac-fe437e626c50&quot;)/div[@class=&quot;opi-panel&quot;]/div[@class=&quot;panel-content&quot;]/div[@class=&quot;site-header flex-row xs-flex-column-start-start&quot;]/site-viz[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;site-display-mount&quot;]/div[@class=&quot;site-viz mt-2&quot;]/div[@class=&quot;horizontal-scroll-container&quot;]/svg[@class=&quot;site-viz-svg&quot;]/g[1]/g[2]/g[@class=&quot;cursor-pointer&quot;]/text[1]</value>
   </webElementProperties>
</WebElementEntity>
