<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>multiple_login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-06-13T08:55:57</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>a5fcb509-2071-4714-a960-845d3d1aeb4a</testSuiteGuid>
   <testCaseLink>
      <guid>f5cfddbf-e9fa-4e30-bb1a-1397b7c528fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OLD_valid_login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>be641f20-7d94-49d1-b7c0-35a6a21571f3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>be641f20-7d94-49d1-b7c0-35a6a21571f3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userName</value>
         <variableId>b1a2190c-34bb-4f85-8bbe-c8799ae740a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>be641f20-7d94-49d1-b7c0-35a6a21571f3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>passWord</value>
         <variableId>caee98cb-741b-4453-92bf-ec7fef9ff52d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
