<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bins</name>
   <tag></tag>
   <elementGuidId>0a9fba2f-9f18-4052-b5e7-9bb714db06ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;grainConditionContainer&quot;)/div[@class=&quot;opi-grain-condition-filters&quot;]/div[@class=&quot;filters-container&quot;]/opi-toggle-filters[@class=&quot;ng-isolate-scope&quot;]/form[@class=&quot;opi-toggle-filters ng-pristine ng-valid&quot;]/div[@class=&quot;title&quot;][count(. | //div[(text() = 'Bins' or . = 'Bins')]) = count(//div[(text() = 'Bins' or . = 'Bins')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-transclude</name>
      <type>Main</type>
      <value>titleSlot</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bins</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grainConditionContainer&quot;)/div[@class=&quot;opi-grain-condition-filters&quot;]/div[@class=&quot;filters-container&quot;]/opi-toggle-filters[@class=&quot;ng-isolate-scope&quot;]/form[@class=&quot;opi-toggle-filters ng-pristine ng-valid&quot;]/div[@class=&quot;title&quot;]</value>
   </webElementProperties>
</WebElementEntity>
