<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon-edit</name>
   <tag></tag>
   <elementGuidId>2418933e-152e-4cc2-bc55-5f7f267cefdc</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-edit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site_5c0d4a94-da3b-4d40-a1c5-968d7047dc2d&quot;)/div[@class=&quot;opi-panel&quot;]/div[@class=&quot;panel-content&quot;]/div[@class=&quot;bin-status-group ng-scope&quot;]/div[@class=&quot;bin-group-container&quot;]/bin-grain-condition[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;opi-bin-grain-condition&quot;]/div[@class=&quot;summary&quot;]/div[@class=&quot;flex-row-centered flex&quot;]/a[1]/i[@class=&quot;icon-edit&quot;]</value>
   </webElementProperties>
</WebElementEntity>
