<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>md-icon_ng-scope</name>
   <tag></tag>
   <elementGuidId>08547b11-f044-46f2-995b-b1030b385a8d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>md-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-svg-icon</name>
      <type>Main</type>
      <value>navigate-next.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewContent&quot;)/account-select[@class=&quot;ng-scope ng-isolate-scope&quot;]/section[@class=&quot;opi-account-select&quot;]/div[@class=&quot;ng-scope&quot;]/div[1]/div[@class=&quot;horizontal-scroll-container&quot;]/md-table-pagination[@class=&quot;md-table-pagination ng-isolate-scope&quot;]/div[@class=&quot;buttons&quot;]/button[@class=&quot;md-icon-button md-button md-ink-ripple&quot;]/md-icon[@class=&quot;ng-scope&quot;]</value>
   </webElementProperties>
</WebElementEntity>
