<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Register</name>
   <tag></tag>
   <elementGuidId>29a68692-5bec-4c2f-b7e3-f6a466fa00e5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/div[1]/div[@class=&quot;container page-login&quot;]/div[@class=&quot;flex-xs-100 flex-60&quot;]/md-card[1]/form[@class=&quot;ng-valid-maxlength ng-dirty ng-valid-required ng-valid ng-valid-parse&quot;]/md-card-actions[@class=&quot;layout-padding layout-align-start-center layout-row&quot;]/button[@class=&quot;md-primary md-raised md-button md-ink-ripple&quot;]/span[@class=&quot;ng-scope&quot;]</value>
   </webElementProperties>
</WebElementEntity>
