<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_edit-btn</name>
   <tag></tag>
   <elementGuidId>3bc50160-c360-4366-b920-bb0d11323927</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.mapCable($index)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Map Cable</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit-btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Map Cable T1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;flex-column modal-open&quot;]/div[@class=&quot;modal fade ng-scope ng-isolate-scope in&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/bin-wizard[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;opi-dialog bs opi-config-sites opi-bin-wizard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;ng-scope&quot;]/bin-wizard-step-5-cable-setup[@class=&quot;ng-scope ng-isolate-scope&quot;]/bin-cable-info-edit[@class=&quot;ng-isolate-scope&quot;]/form[@class=&quot;opi-form bin-cable-info ng-pristine ng-valid&quot;]/div[@class=&quot;flex-row mt-4&quot;]/div[@class=&quot;flex-grow flex-grow-xs-off&quot;]/div[@class=&quot;opi-flex-table&quot;]/div[@class=&quot;unmapped-cable flex-row-space-between align-center full-row ng-scope temperature-cable&quot;]/a[@class=&quot;edit-btn&quot;]</value>
   </webElementProperties>
</WebElementEntity>
