<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Blackbean</name>
   <tag></tag>
   <elementGuidId>9c15f081-9f7a-44fa-8be2-37f8250c0926</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-checkbox-label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>gmkd0a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blackbean</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grainConditionContainer&quot;)/div[@class=&quot;opi-grain-condition-filters&quot;]/div[@class=&quot;filters-container&quot;]/opi-toggle-filters[@class=&quot;ng-isolate-scope&quot;]/form[@class=&quot;opi-toggle-filters ng-pristine ng-valid&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;check-box-wrapper&quot;]/label[@class=&quot;custom-checkbox-label&quot;]</value>
   </webElementProperties>
</WebElementEntity>
