<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon-plus_1</name>
   <tag></tag>
   <elementGuidId>2633c7f2-ee1e-4d46-adb1-92224ace72d3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-plus</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;flex-column modal-open&quot;]/div[@class=&quot;modal fade ng-scope ng-isolate-scope in&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/bin-wizard[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;opi-dialog bs opi-config-sites opi-bin-wizard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;ng-scope&quot;]/bin-wizard-step-5-cable-setup[@class=&quot;ng-scope ng-isolate-scope&quot;]/bin-cable-info-edit[@class=&quot;ng-isolate-scope&quot;]/form[@class=&quot;opi-form bin-cable-info ng-pristine ng-valid&quot;]/div[@class=&quot;flex-row mt-4&quot;]/div[@class=&quot;flex-grow flex-grow-xs-off&quot;]/div[@class=&quot;opi-flex-table&quot;]/div[@class=&quot;unmapped-cable flex-row-space-between align-center full-row ng-scope temperature-cable&quot;]/a[@class=&quot;edit-btn&quot;]/i[@class=&quot;icon-plus&quot;]</value>
   </webElementProperties>
</WebElementEntity>
