<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Continue</name>
   <tag></tag>
   <elementGuidId>2d580eef-f78d-4a06-80bd-c4cca7cddc52</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>vm.wizard</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding ng-scope</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;flex-column modal-open&quot;]/div[@class=&quot;modal fade ng-scope ng-isolate-scope in&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/bin-wizard[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;opi-dialog bs opi-config-sites opi-bin-wizard&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;ng-scope&quot;]/bin-wizard-step2-grain-info[@class=&quot;ng-scope ng-isolate-scope&quot;]/bin-grain-info-edit[@class=&quot;ng-isolate-scope&quot;]/form[@class=&quot;opi-form ng-valid-min ng-valid-max ng-valid-step ng-dirty ng-valid-parse ng-valid ng-valid-required&quot;]/div[@class=&quot;opi-spaced-buttons&quot;]/button[@class=&quot;opi-btn primary lg&quot;]/span[@class=&quot;ng-binding ng-scope&quot;]</value>
   </webElementProperties>
</WebElementEntity>
