<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon-pencil_1</name>
   <tag></tag>
   <elementGuidId>8a67b8d3-c4c9-4fda-91dd-f09b0fc0bfa3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-pencil</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;flex-column modal-open&quot;]/div[@class=&quot;modal fade ng-scope ng-isolate-scope in&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/bin-details-container[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;opi-dialog bs opi-config-sites&quot;]/div[@class=&quot;content&quot;]/bin-cable-info-edit[@class=&quot;ng-scope ng-isolate-scope&quot;]/form[@class=&quot;opi-form bin-cable-info ng-pristine ng-valid&quot;]/div[@class=&quot;flex-row&quot;]/div[@class=&quot;flex-grow flex-grow-xs-off&quot;]/div[@class=&quot;opi-flex-table-holder&quot;]/div[@class=&quot;opi-flex-table&quot;]/div[@class=&quot;mapped-cable flex-grow ng-scope temperature-cable&quot;]/div[@class=&quot;row flex-row-space-between align-center&quot;]/a[@class=&quot;edit-btn&quot;]/i[@class=&quot;icon-pencil&quot;]</value>
   </webElementProperties>
</WebElementEntity>
