<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_FirstBin</name>
   <tag></tag>
   <elementGuidId>d0a29518-2fd8-4056-898f-2cb698e474f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;site_ec041b07-3a2f-41f5-9fac-fe437e626c50&quot;)/div[@class=&quot;opi-panel&quot;]/div[@class=&quot;panel-content&quot;]/div[@class=&quot;site-header flex-row xs-flex-column-start-start&quot;]/site-viz[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;site-display-mount&quot;]/div[@class=&quot;site-viz mt-2&quot;]/div[@class=&quot;horizontal-scroll-container&quot;]/svg[@class=&quot;site-viz-svg&quot;]/g[1]/g[1]/g[@class=&quot;cursor-pointer&quot;]/text[1][count(. | //text[(text() = 'FirstBin' or . = 'FirstBin')]) = count(//text[(text() = 'FirstBin' or . = 'FirstBin')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dx</name>
      <type>Main</type>
      <value>22.5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dy</name>
      <type>Main</type>
      <value>48</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-anchor</name>
      <type>Main</type>
      <value>middle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-family</name>
      <type>Main</type>
      <value>Verdana</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>12</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>black</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FirstBin</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site_ec041b07-3a2f-41f5-9fac-fe437e626c50&quot;)/div[@class=&quot;opi-panel&quot;]/div[@class=&quot;panel-content&quot;]/div[@class=&quot;site-header flex-row xs-flex-column-start-start&quot;]/site-viz[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;site-display-mount&quot;]/div[@class=&quot;site-viz mt-2&quot;]/div[@class=&quot;horizontal-scroll-container&quot;]/svg[@class=&quot;site-viz-svg&quot;]/g[1]/g[1]/g[@class=&quot;cursor-pointer&quot;]/text[1]</value>
   </webElementProperties>
</WebElementEntity>
